version: '3.4'

services:
  admin:
    #build: 
    #    context: .\ems-web-only
    image: kentico/xperience-13-core:admin-13.0.12-preview
    ports:
      - 60051:80
    links:
      - sql
    depends_on:
      - sql    

  sql:
    #build: 
    #    context: .\ems-db
    #environment:
    #  - sa_password=Pass@word1
    #  - ACCEPT_EULA=Y
    #image: microsoft/mssql-server-windows-express
    image: kentico/xperience-13-core:sql-13.0.12-preview
    ports:
      - 1435:1433
  
  web:
    image: kentico/xperience-13-core:web-13.0.12-preview
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    # volumes: 
    #   - ./web/dancinggoatcore_3:c:/kx/dancinggoatcore
    links:
      - sql
      - admin
    depends_on:
      - sql    
